import { defaultCache } from "@serwist/next/worker";
import type { PrecacheEntry, SerwistGlobalConfig } from "serwist";
import { Serwist, NetworkFirst, CacheFirst } from "serwist";

// This declares the value of `injectionPoint` to TypeScript.
// `injectionPoint` is the string that will be replaced by the
// temporary precache manifest generated by the Serwist build step.
declare global {
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

declare const self: ServiceWorkerGlobalScope;

const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching: [
    // Cache API responses for user schedules (escalas)
    {
      matcher: ({ url }) => {
        return url.pathname.startsWith("/api/escalas") ||
               url.pathname.startsWith("/api/schedules") ||
               url.pathname.startsWith("/api/user/schedules");
      },
      handler: new NetworkFirst({
        cacheName: "api-schedules-cache",
        plugins: [
          {
            cacheWillUpdate: async ({ response }) => {
              if (response && response.status === 200) {
                return response;
              }
              return null;
            },
          },
        ],
        networkTimeoutSeconds: 10,
      }),
    },
    // Cache API responses for events
    {
      matcher: ({ url }) => {
        return url.pathname.startsWith("/api/eventos") ||
               url.pathname.startsWith("/api/events");
      },
      handler: new NetworkFirst({
        cacheName: "api-events-cache",
        plugins: [
          {
            cacheWillUpdate: async ({ response }) => {
              if (response && response.status === 200) {
                return response;
              }
              return null;
            },
          },
        ],
        networkTimeoutSeconds: 10,
      }),
    },
    // Cache other API responses
    {
      matcher: ({ url }) => {
        return url.pathname.startsWith("/api/");
      },
      handler: new NetworkFirst({
        cacheName: "api-cache",
        plugins: [
          {
            cacheWillUpdate: async ({ response }) => {
              if (response && response.status === 200) {
                return response;
              }
              return null;
            },
          },
        ],
        networkTimeoutSeconds: 10,
      }),
    },
    // Cache static assets (images, fonts, etc.)
    {
      matcher: ({ request }) => {
        return request.destination === "image" ||
               request.destination === "font" ||
               request.destination === "style";
      },
      handler: new CacheFirst({
        cacheName: "static-assets-cache",
        plugins: [
          {
            cacheWillUpdate: async ({ response }) => {
              if (response && (response.status === 0 || response.status === 200)) {
                return response;
              }
              return null;
            },
          },
        ],
      }),
    },
    // Cache Google Fonts
    {
      matcher: ({ url }) => {
        return url.origin === "https://fonts.googleapis.com" ||
               url.origin === "https://fonts.gstatic.com";
      },
      handler: new CacheFirst({
        cacheName: "google-fonts-cache",
        plugins: [
          {
            cacheWillUpdate: async ({ response }) => {
              if (response && (response.status === 0 || response.status === 200)) {
                return response;
              }
              return null;
            },
          },
        ],
      }),
    },
    // Default cache configuration
    ...defaultCache,
  ],
  fallbacks: {
    entries: [
      {
        url: "/offline",
        matcher: ({ request }) => request.destination === "document",
      },
    ],
  },
});

// Listen for messages from the client
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

serwist.addEventListeners();
